In [1]:
import polarizability as pol
import staticraman as raman
import numpy as np
from pyscf import gto, dft, grad, scf

mol = gto.M(atom='''O 0.0000000    0.000000    0.115720
                    H 0.0000000    0.748790   -0.462879
                    H 0.0000000   -0.748790   -0.462879''',
            basis='ccpvdz')
raman.get_raman_activities_RHF(mol)


/home/zc62/pyscf/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, the same to the B3LYP functional in Gaussian and ORCA (issue 1480). To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '


converged SCF energy = -76.0270535127373
Polarizability (unit: Angstrom**3):
[[ 4.51126099e-01 -2.03806777e-16  8.06527993e-16]
 [-2.44035150e-13  9.91823727e-01 -6.51217394e-13]
 [-2.63118683e-09  3.97262128e-13  7.37741695e-01]]
--------------- RHF gradients ---------------
         x                y                z
0 O    -0.0000000000    -0.0000000000     0.0000047368
1 H     0.0000000000     0.0000023609    -0.0000023684
2 H    -0.0000000000    -0.0000023609    -0.0000023684
----------------------------------------------
frequency: 1775.6672868371343 cm^-1
Mass-weighted normal mode:
[[-2.90049724e-18  2.07338527e-11  7.02065571e-02]
 [ 1.51948700e-17 -4.32560022e-01 -5.57160073e-01]
 [ 2.25097362e-17  4.32560022e-01 -5.57160073e-01]]
Polarizability derivative w.r.t. this mode (unit: Angstrom**2/sqrt(amu)):
[[ 7.81018520e-03  5.89799006e-11 -8.63080002e-13]
 [ 1.18475866e-10 -1.99858510e-01  4.45569796e-10]
 [-3.90254034e-07  1.88275936e-10  6.24098563e-01]]
Raman activity (unit:

array([ 4.78978723, 68.87518138, 34.78691755])

Gaussian 16 input:
```
%nproc=8
%mem=1GB
#p RHF/cc-pvdz opt(tight) freq(raman,printderivatives)

Water

0 1
O   0.000000   -0.000000    0.115720
H   0.000000    0.748790   -0.462879
H   0.000000   -0.748790   -0.462879



```

Gaussian 16 output:
```
 Dipole        =-2.65629798D-17 8.99983592D-18-8.04258767D-01
 Polarizability= 3.04435455D+00 2.64508543D-16 6.69315754D+00
                 1.89584259D-16 4.44089210D-16 4.97852778D+00
 HyperPolar    =-2.25277130D-16-2.14336914D-15-1.31850706D-15
                -7.54465692D-15-2.33976823D+00-1.11020113D-15
                -1.61994555D+01-6.31148860D-16-4.93925592D-15
                -1.02446193D+01
 Full mass-weighted force constant matrix:
 Low frequencies ---   -0.0023   -0.0022   -0.0016    6.6951    7.3313    8.4007
 Low frequencies --- 1775.8275 4113.7285 4212.0547
 Dipole derivative wrt mode   1:  1.48077D-15 -8.14989D-15  8.98322D+00
 Polarizability derivatives wrt mode          1
                 1             2             3
      1  -0.781020D-02  0.000000D+00  0.000000D+00
      2   0.000000D+00  0.199879D+00  0.000000D+00
      3   0.000000D+00  0.000000D+00 -0.624154D+00
 Vibrational polarizability contributions from mode   1       0.0000000       0.0000000       0.6886453
 Vibrational hyperpolarizability contributions from mode   1      -0.0000000      -0.0000000      -5.3349284
 IFr=  0 A012= 0.28D+00 0.39D+01 0.64D+00 Act= 0.48D+01 DepolP= 0.53D+00 DepolU= 0.69D+00
 Dipole derivative wrt mode   2: -6.35845D-15 -1.83171D-13 -4.60180D+00
 Polarizability derivatives wrt mode          2
                 1             2             3
      1  -0.389012D-01  0.000000D+00  0.000000D+00
      2   0.000000D+00  0.207055D+01  0.000000D+00
      3   0.000000D+00  0.000000D+00  0.985624D+00
 Vibrational polarizability contributions from mode   2       0.0000000       0.0000000       0.0336758
 Vibrational hyperpolarizability contributions from mode   2       0.0000000      -0.0000000      -0.8042193
 IFr=  0 A012= 0.14D+02 0.47D+02 0.79D+01 Act= 0.69D+02 DepolP= 0.17D+00 DepolU= 0.29D+00
 Dipole derivative wrt mode   3:  6.17638D-15  7.77682D+00 -1.11514D-13
 Polarizability derivatives wrt mode          3
                 1             2             3
      1   0.000000D+00  0.000000D+00  0.000000D+00
      2   0.000000D+00  0.000000D+00 -0.128717D+01
      3   0.000000D+00 -0.128717D+01  0.000000D+00
 Vibrational polarizability contributions from mode   3       0.0000000       0.0917380       0.0000000
 Vibrational hyperpolarizability contributions from mode   3      -0.0000000       0.0000000      -0.0000000
 IFr=  0 A012= 0.68D-26 0.30D+02 0.50D+01 Act= 0.35D+02 DepolP= 0.75D+00 DepolU= 0.86D+00
 Diagonal vibrational polarizability:
        0.0000000       0.0917380       0.7223211
 Diagonal vibrational hyperpolarizability:
        0.0000000      -0.0000000      -6.1391477
 Harmonic frequencies (cm**-1), IR intensities (KM/Mole), Raman scattering
 activities (A**4/AMU), depolarization ratios for plane and unpolarized
 incident light, reduced masses (AMU), force constants (mDyne/A),
 and normal coordinates:
                      1                      2                      3
                     A1                     A1                     B2
 Frequencies --   1775.8275              4113.7285              4212.0547
 Red. masses --      1.0817                 1.0461                 1.0820
 Frc consts  --      2.0098                10.4300                11.3097
 IR Inten    --     80.6982                21.1766                60.4790
 Raman Activ --      4.7906                68.8874                34.7930
 Depolar (P) --      0.5269                 0.1701                 0.7500
 Depolar (U) --      0.6901                 0.2908                 0.8571
  Atom  AN      X      Y      Z        X      Y      Z        X      Y      Z
     1   8    -0.00  -0.00  -0.07     0.00   0.00   0.05    -0.00  -0.07   0.00
     2   1     0.00   0.43   0.56     0.00   0.58  -0.40     0.00   0.56  -0.43
     3   1     0.00  -0.43   0.56    -0.00  -0.58  -0.40     0.00   0.56   0.43
```
and
```
 Electric dipole moment (input orientation):
 (Debye = 10**-18 statcoulomb cm , SI units = C m)
                  (au)            (Debye)         (10**-30 SI)
   Tot        0.804259D+00      0.204422D+01      0.681879D+01
   x          0.000000D+00      0.000000D+00      0.000000D+00
   y          0.000000D+00      0.000000D+00      0.000000D+00
   z         -0.804259D+00     -0.204422D+01     -0.681879D+01

 Dipole polarizability, Alpha (input orientation).
 (esu units = cm**3 , SI units = C**2 m**2 J**-1)
 Alpha(0;0):
               (au)            (10**-24 esu)      (10**-40 SI)
   iso        0.490535D+01      0.726897D+00      0.808782D+00
   aniso      0.316186D+01      0.468540D+00      0.521321D+00
   xx         0.304435D+01      0.451127D+00      0.501946D+00
   yx         0.000000D+00      0.000000D+00      0.000000D+00
   yy         0.669316D+01      0.991824D+00      0.110355D+01
   zx         0.000000D+00      0.000000D+00      0.000000D+00
   zy         0.000000D+00      0.000000D+00      0.000000D+00
   zz         0.497853D+01      0.737742D+00      0.820848D+00
```